
parameters:

    locale: 'en'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $eventId: 6985
            $debug: '%kernel.debug%'
            $apiPath: '/api'

    _instanceof:
        App\JoindIn\Plugin:
            tags: ['api_plugin']

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Negotiation\Negotiator: ~

    GuzzleHttp\Client: ~









    #GuzzleHttp\Handler\CurlHandler: ~

    #GuzzleHttp\HandlerStack:
    #    calls:
    #        - [ setHandler, ['@GuzzleHttp\Handler\CurlHandler']]


    #    arguments: [[handler: '@GuzzleHttp\HandlerStack']]
